/**
 * Content access for ecuahuecas.
 *
 * The state is REACTIVE (Vue refs) and seeded SYNCHRONOUSLY at import time from
 * the build-time Sanity SNAPSHOT (`src/content-snapshot.json`, generated by
 * `scripts/snapshot-sanity.mjs`). The JSON inlines at build time — SSG-friendly
 * and zero runtime fetch on first paint, so prerendered pages + SEO are intact.
 *
 * On the client, `refreshContent()` fetches the same docs LIVE from Sanity
 * (tokenless, public CDN — see `src/lib/sanityContent.ts`) and REPLACES the
 * reactive state. App.vue calls it once in `onMounted`, so edits made in Sanity
 * appear on the next page reload WITHOUT a rebuild/deploy. NEVER call it during
 * SSR/prerender (no Sanity at module eval; the import below is the only data the
 * server uses).
 *
 * The exported helper names/signatures are unchanged; they now read the CURRENT
 * reactive state, so `computed()` wrappers in pages re-evaluate after a refresh.
 * Pages that previously read `huecas`/`resenas`/`criticos` as plain arrays must
 * now read `.value` (they are `Ref<...>`).
 */
import { ref } from 'vue'
import snapshot from '../content-snapshot.json'
import type {
  ContentSnapshot,
  Hueca as HuecaT,
  Resena as ResenaT,
  Critico as CriticoT,
} from '@/types/content'
import { fetchContent } from './sanityContent'

const seed = snapshot as ContentSnapshot

// Reactive state, seeded from the static snapshot (SSR-safe, sync).
export const huecas = ref<HuecaT[]>(seed.huecas)
export const resenas = ref<ResenaT[]>(seed.resenas)
export const criticos = ref<CriticoT[]>(seed.criticos)

/**
 * Refresh the reactive state from a LIVE Sanity read (browser only). Best-effort:
 * any failure (offline, transient CDN error) is swallowed so the page keeps the
 * snapshot seed rather than blanking out. Returns void.
 */
export async function refreshContent(): Promise<void> {
  try {
    const live = await fetchContent()
    huecas.value = live.huecas
    resenas.value = live.resenas
    criticos.value = live.criticos
  } catch (err) {
    // Keep the snapshot seed; live refresh is an enhancement, not a requirement.
    if (import.meta.env.DEV) console.warn('[content] live refresh failed:', err)
  }
}

export function getHueca(slug: string): HuecaT | undefined {
  return huecas.value.find((h) => h.slug === slug)
}

export function getResena(slug: string): ResenaT | undefined {
  return resenas.value.find((r) => r.slug === slug)
}

export function getCritico(slug: string): CriticoT | undefined {
  return criticos.value.find((c) => c.slug === slug)
}

export function resenasDeHueca(hueca_id: string): ResenaT[] {
  return resenas.value.filter((r) => r.hueca_id === hueca_id)
}

export function huecasDeCiudad(ciudad: string): HuecaT[] {
  return huecas.value.filter((h) => h.ciudad === ciudad)
}

export function huecasTop(n: number = 10): HuecaT[] {
  return [...huecas.value].sort((a, b) => b.rating - a.rating).slice(0, n)
}
