/**
 * Content access for ecuahuecas.
 *
 * Data comes from the build-time Sanity SNAPSHOT (`src/content-snapshot.json`,
 * generated by `scripts/snapshot-sanity.mjs`). The JSON is imported STATICALLY
 * so it inlines at build time — SSG-friendly and zero runtime fetch, so
 * anonymous readers get fully prerendered pages.
 *
 * The exported helper names/signatures are unchanged from the previous
 * markdown-backed implementation, so page consumers barely change.
 */
import snapshot from '../content-snapshot.json'
import type {
  ContentSnapshot,
  Hueca as HuecaT,
  Resena as ResenaT,
  Critico as CriticoT,
} from '@/types/content'

const data = snapshot as ContentSnapshot

export const huecas: HuecaT[] = data.huecas
export const resenas: ResenaT[] = data.resenas
export const criticos: CriticoT[] = data.criticos

export function getHueca(slug: string): HuecaT | undefined {
  return huecas.find((h) => h.slug === slug)
}

export function getResena(slug: string): ResenaT | undefined {
  return resenas.find((r) => r.slug === slug)
}

export function getCritico(slug: string): CriticoT | undefined {
  return criticos.find((c) => c.slug === slug)
}

export function resenasDeHueca(hueca_id: string): ResenaT[] {
  return resenas.filter((r) => r.hueca_id === hueca_id)
}

export function huecasDeCiudad(ciudad: string): HuecaT[] {
  return huecas.filter((h) => h.ciudad === ciudad)
}

export function huecasTop(n: number = 10): HuecaT[] {
  return [...huecas].sort((a, b) => b.rating - a.rating).slice(0, n)
}
